spring:
  thymeleaf:
    cache: false # 关闭thymeleaf缓存
  profiles:
    active: dev
    # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://101.37.22.230:3306/co-shopping?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    #mysql8版本以上驱动包指定新的驱动类
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  mail:
    host: smtp.qq.com
    username: jinke12138@foxmail.com
    password: uynuhfduimuzbbai
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

mybatis-plus:
  # 指定实体类所有包
  type-aliases-package: sydney.edu.au.web.entity
  mapper-locations: classpath:/mapper/*Mapper.xml

# 日志级别，会打印sql语句
logging:
  level:
    sydney.edu.au.web.mapper: debug

co-shopping:
  jwt:
    config:
      secretKey: co-shopping # jwt token secret key
      expires: 604800 # unit second ，seven days
#server:
  port: 9000
server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
